<<<<<<< HEAD
spring.application.name=course-jpa-example

#data source:
=======
spring.application.name=course-jdbc-example

>>>>>>> 3746a2ce3f1ace51d21d7c679963c9f122865919
spring.datasource.url=jdbc:mysql://localhost:3306/jb2404
spring.datasource.username=root
spring.datasource.password=787947

<<<<<<< HEAD
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver




#jpa or hibernate onfiguration-

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto =update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect







#none-hibernate will not manage
#validate-hibernate will validate the schema agianst your entities but will not make any changes
#update-hibernate will modify the schema to match the entity definations but will not drop
#create-will create schema every time

#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

#Dialect Hibernate ko batata hai:
#"Is particular database ki language me SQL kaise likhni hai"
=======
spring.sql.init.mode = always

#spring.sql.init.schema-locations=classpath:/filename.sql
>>>>>>> 3746a2ce3f1ace51d21d7c679963c9f122865919
