spring:
  application:
    name: food-service

  datasource:
    url: jdbc:mysql://localhost:3306/jb2404?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 787947
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

server:
  port: 9092