spring:
  application:
    name: "food-service"


  config:
    import: "configserver:http://localhost:9096/"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      defaults:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000